### PR TITLE
Example: Fix alpha channel in examples/vignette.rb

### LINKED ISSUE #907: vignette.rb example generates different image with ImageMagick 7
## Test code
https://github.com/rmagick/rmagick/blob/master/examples/vignette.rb

### Result
with IM6 | with IM7
-- | --
 |

### PR DESCRIPTION
**Pull request by Watson1978**
Fix #907

### CODE REVIEW

File: examples/vignette.rb [hunk 1]
```diff
@@ -74,5 +74,5 @@
 
 checkerboard = Image.read('pattern:checkerboard') { self.size = "#{ballerina.columns}x#{ballerina.rows}" }
 vignette = checkerboard[0].composite(ballerina, CenterGravity, OverCompositeOp)
-vignette.write('vignette.png')
+vignette.write('vignette1.png')
```
Comment (mockdeep) [inline examples/vignette.rb]: @Watson1978 why was this renamed?

Comment (Watson1978) [reply examples/vignette.rb]: https://github.com/rmagick/rmagick/blob/b6a448e5deb557ce794f75b2e65b4f4b537f2d4e/examples/vignette.rb#L65

It override the image.
I wanted to check both.
