### PR TITLE
Fix a bug which ImageList#montage doesn't apply border_color & matte_color

### LINKED ISSUE #1: RMagick ignoring border_color
<a href="https://github.com/rggjan"></img></a> **Issue by [rggjan](https://github.com/rggjan)**
_Tuesday Feb 23, 2010 at 13:50 GMT_
_Originally opened as https://github.com/rmagick/rmagick/issues/1_

---

With this code:

``` ruby
#!/usr/bin/ruby
require 'RMagick'
include Magick

imagelist=ImageList.new('/home/jan/Desktop/test.jpg')

collage = imagelist.montage do
  self.border_color='red'
  self.border_width=10
  self.geometry=Geometry.new(500, 500)
end

collage.write('/home/jan/Desktop/test_collage.jpg')

IMGCOMMAND="-border 10x10 -bordercolor red -geometry 500x500 /home/jan/Desktop/test_collage_original.jpg"
system "montage /home/jan/Desktop/test.jpg " + IMGCOMMAND
```

A red border is created with the original imagemagick (test_collage_original) while it is white with Rmagick (test_collage). It should be red in both cases...

### PR DESCRIPTION
**Pull request by Watson1978**
Fix #1

According to ImageMagick's Perl bridge,
https://github.com/ImageMagick/ImageMagick6/blob/8ed8ee76dd5fcfc3d182cf00c5696508425176b4/PerlMagick/quantum/quantum.xs.in#L11332-L11333

we need to apply `border_color` in MontageInfo to `image->border_color` manually like `image->compose`.
And this patch also change `background_color`, `matte_color` and `gravity` according to the Perl bridge.

* background
https://github.com/ImageMagick/ImageMagick6/blob/8ed8ee76dd5fcfc3d182cf00c5696508425176b4/PerlMagick/quantum/quantum.xs.in#L11319-L11320

* mattecolor
https://github.com/ImageMagick/ImageMagick6/blob/8ed8ee76dd5fcfc3d182cf00c5696508425176b4/PerlMagick/quantum/quantum.xs.in#L11465-L11466

* gravity
https://github.com/ImageMagick/ImageMagick6/blob/8ed8ee76dd5fcfc3d182cf00c5696508425176b4/PerlMagick/quantum/quantum.xs.in#L11435-L11436

### Test code
```
require 'rmagick'

imagelist = Magick::ImageList.new('in.png')

collage = imagelist.montage do
  self.border_width = 100
  self.border_color = 'red'
  self.background_color = 'blue'
  self.matte_color = 'yellow'
  self.frame = '10x10'
  self.gravity = Magick::StaticGravity
end

collage.write('out.png')
```

* Input image
in

* Result

Before | After
-- | --
 | 

(by ImageMagick)
```
$ ~/imagemagick6.9/bin/montage in.png -border 100x100 -bordercolor red -mattecolor yellow -background blue -frame 10x10 out2.png
```

out2

### CODE REVIEW

**Comment by mockdeep** [comment]
Haha, great! The first bug is now dead!

File: ext/RMagick/rmagick.h [hunk 1]
```diff
@@ -46,6 +46,13 @@
 
 #include "extconf.h"
 
+#ifndef TRUE
```
Comment (mockdeep) [inline ext/RMagick/rmagick.h]: Can we do `#define` here instead of `#ifndef`, or are there cases when it might already be defined?

File: ext/RMagick/rmagick.h [hunk 2]
```diff
@@ -121,6 +128,13 @@ typedef PixelPacket PixelColor;
 //! Montage
 typedef struct
 {
+    struct _change
```
Comment (mockdeep) [inline ext/RMagick/rmagick.h]: Why do we need the `_change` here? Is this a convention for clarity?

File: ext/RMagick/rmilist.c [hunk 3]
```diff
@@ -504,13 +505,23 @@ ImageList_montage(VALUE self)
...
-    if (montage->compose != UndefinedCompositeOp)
+    for (image = images; image; image = GetNextImageInList(image))
     {
-        Image *i;
-        for (i = images; i; i = GetNextImageInList(i))
+        if (montage->compose != UndefinedCompositeOp)
+        {
+            image->compose = montage->compose;
+        }
+        if (montage->change.background_color)
```
Comment (mockdeep) [inline ext/RMagick/rmilist.c]: What is the difference between `->` and `.` here?

File: ext/RMagick/rmagick.h (hunk 2 above)
Comment (Watson1978) [reply ext/RMagick/rmagick.h]: it need to mark the properties that apply the changed. it is just namespace.

If you like flat style, it will be as following.
```
int change_background_color;
int change_border_color;
int change_gravity;
```

File: ext/RMagick/rmilist.c (hunk 3 above)
Comment (Watson1978) [reply ext/RMagick/rmilist.c]: it use `->` when a member of a structure is a pointer variable.

File: ext/RMagick/rmagick.h (hunk 2 above)
Comment (mockdeep) [reply ext/RMagick/rmagick.h]: I see. Thanks for the explanation. I think what you have is good.

File: ext/RMagick/rmagick.h (hunk 1 above)
Comment (Watson1978) [reply ext/RMagick/rmagick.h]: Since `TRUE` is a common name, it might be add in other header files.
So, i think it is better to guard.

Without definition, it caused compile error....

File: ext/RMagick/rmilist.c [hunk 4]
```diff
@@ -504,13 +505,23 @@ ImageList_montage(VALUE self)
 
     images = images_from_imagelist(self);
 
-    // If app specified a non-default composition operator, use it for all images.
-    if (montage->compose != UndefinedCompositeOp)
+    for (image = images; image; image = GetNextImageInList(image))
     {
-        Image *i;
-        for (i = images; i; i = GetNextImageInList(i))
+        if (montage->compose != UndefinedCompositeOp)
```
Comment (dlemstra) [inline ext/RMagick/rmilist.c]: Do we really need this check? Can't we always set it?

File: ext/RMagick/rmilist.c [hunk 5]
```diff
@@ -504,13 +505,23 @@ ImageList_montage(VALUE self)
...
+        {
+            image->compose = montage->compose;
+        }
+        if (montage->change.background_color)
+        {
+            image->background_color = montage->info->background_color;
+        }
+        if (montage->change.border_color)
```
Comment (dlemstra) [inline ext/RMagick/rmilist.c]: I really wonder if we need these values to check if it was set by the user. Shouldn't we always set the `*_color` to the value of the montage info?

Comment (Watson1978) [reply ext/RMagick/rmilist.c]: I think we should apply the value only when user set. I don't know what correct usage in ImageMagick. But, if we don't use MontageInfo for color, we have to change the interface.

Comment (dlemstra) [reply ext/RMagick/rmilist.c]: But if the image background color is red and the `MontageInfo` has the default color (white/black?) should we not use that instead?

**Comment by dlemstra** [comment]
Could you also add some tests for these changes?

**Comment by Watson1978** [comment]
@dlemstra How do we write a test to check the appearance? Seems there is no test in RMagick so far...

**Comment by dlemstra** [comment]
You could also check if the background color of the image has changed? And we really also need some tests to check appearance. In Magick.NET I just check the value of individual colors. Maybe we could write our own assertion for the color of a pixel? But that should maybe something for a new PR?

File: ext/RMagick/rmilist.c (hunk 5 above)
Comment (Watson1978) [reply ext/RMagick/rmilist.c]: we should set the color what user desired via Montage#border_color ....

**Comment by Watson1978** [comment]
I think we should construct a way to check the appearance for support ImageMagick 7 and 6.

**Comment by Watson1978** [comment]
Hmm, I foud `matte_color` need same way to apply

File: ext/RMagick/rmilist.c (hunk 5 above)
Comment (dlemstra) [reply ext/RMagick/rmilist.c]: But why should we only do this when the user has changed the value? Shouldn't we always use the default value instead? If the users sees the color is black and decides not to change it because that is the value that they want to use but then we don't use it because the user did not explicitly set it?

Comment (Watson1978) [reply ext/RMagick/rmilist.c]: If image has user expected value, I think user doesn't need to change.

Comment (dlemstra) [reply ext/RMagick/rmilist.c]: This the call that is being made: `MontageImages(images, montage->info, exception);`. It is now possible that `montage->info->border_color` has a different value than `image->border_color`. I wonder if the `changed` checks should be removed to make sure they have the same value.

Comment (mockdeep) [reply ext/RMagick/rmilist.c]: I'm not sure I fully understand this, but I think I agree with @dlemstra. If the user calls the method, I think it should have *some* result, even if they haven't put in values, rather than silently doing nothing. If we do nothing, it could be confusing to the user why nothing is happening, but if we change the background color to something different than what they expect, they'll have a better idea of where to look. It also seems like it'll make for much cleaner code.

**Comment by Watson1978** [comment]
@dlemstra @mockdeep  I fixed this PR with your opinion and added test for appearance. Can you review this ?

File: test/appearance/Montage.rb [hunk 6]
```diff
@@ -0,0 +1,26 @@
...
+    new_imagelist = imagelist.montage do
+      self.border_width = 100
+      self.border_color = 'red'
+      self.background_color = 'blue'
+      self.matte_color = 'yellow'
+      self.frame = '10x10'
+      self.gravity = Magick::StaticGravity
+    end
+
+    # montage ../../doc/ex/images/Flower_Hat.jpg -border 100x100 -bordercolor red -mattecolor yellow -background blue -frame 10x10 expected/montage_border_color.png
```
Comment (dlemstra) [inline test/appearance/Montage.rb]: Should `-border 100x100` not be `-border 100x` instead?

File: test/appearance/Montage.rb [hunk 7]
```diff
@@ -0,0 +1,26 @@
...
+  def test_color
+    imagelist = Magick::ImageList.new(IMAGES_DIR + '/Flower_Hat.jpg')
+
+    new_imagelist = imagelist.montage do
+      self.border_width = 100
+      self.border_color = 'red'
+      self.background_color = 'blue'
+      self.matte_color = 'yellow'
+      self.frame = '10x10'
+      self.gravity = Magick::StaticGravity
```
Comment (dlemstra) [inline test/appearance/Montage.rb]: `Magick::StaticGravity` is deprecated. Please change this to `Magick::CenterGravity`.

File: test/appearance/Montage.rb (hunk 6 above)
Comment (dlemstra) [inline test/appearance/Montage.rb]: `-gravity` is missing?

Comment (Watson1978) [reply test/appearance/Montage.rb]: Thanks. Fixed.

File: test/appearance/Montage.rb (hunk 7 above)
Comment (Watson1978) [reply test/appearance/Montage.rb]: Thanks. Fixed.

File: test/appearance/Montage.rb (hunk 6 above)
Comment (Watson1978) [reply test/appearance/Montage.rb]: Thanks. Fixed.

**Comment by dlemstra** [comment]
LGTM now, can you take another look at this @mockdeep?

File: test/appearance/appearance_assertion.rb [hunk 8]
```diff
@@ -0,0 +1,13 @@
+require 'test/unit'
+
+module AppearanceAssertion
+  include Test::Unit::Assertions
+
+  def assert_same_image(expected_image_path, image_object, delta = 0.01)
+    path = File.expand_path(File.join(__FILE__, '..', expected_image_path))
```
Comment (mockdeep) [inline test/appearance/appearance_assertion.rb]: I believe you can use `__dir__` here in place of `__FILE__, '..'`.

File: test/appearance/appearance_assertion.rb [hunk 9]
```diff
@@ -0,0 +1,13 @@
+require 'test/unit'
+
+module AppearanceAssertion
+  include Test::Unit::Assertions
+
+  def assert_same_image(expected_image_path, image_object, delta = 0.01)
```
Comment (mockdeep) [inline test/appearance/appearance_assertion.rb]: For the image above, should the delta be `0.0`?

Comment (mockdeep) [reply test/appearance/appearance_assertion.rb]: Also, I wonder if we should leave the `delta` argument out for now, until we need it.

Comment (Watson1978) [reply test/appearance/appearance_assertion.rb]: There seems to be a subtle error between the ImageMagick versions.

File: test/appearance/appearance_assertion.rb (hunk 8 above)
Comment (Watson1978) [reply test/appearance/appearance_assertion.rb]: Ah, nice 👍

File: test/appearance/appearance_assertion.rb (hunk 9 above)
Comment (mockdeep) [reply test/appearance/appearance_assertion.rb]: I see. In that case, should we make `delta` a keyword argument? `delta: 0.01`.

Comment (Watson1978) [reply test/appearance/appearance_assertion.rb]: OK I see.

**Comment by Watson1978** [comment]
Thanks😆
